import os
import json
import re

exam_dir = 'public/exam-ram1201'
files = [f for f in os.listdir(exam_dir) if f.startswith('questions_ch') and f.endswith('.js')]

def validate_quiz_file(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Extract the JSON array part
        match = re.search(r'const questions_ch\d+\s*=\s*(\[.*\]);?', content, re.DOTALL)
        if not match:
            return "Failed to find JavaScript array assignment."
            
        json_str = match.group(1)
        # Some JS might have trailing commas or single quotes which standard JSON doesn't like,
        # but let's try strict JSON parsing first, or just use a simple eval-like approach if needed.
        # Since it was generated by an LLM, it's usually valid JSON.
        
        # Clean up possible trailing commas
        json_str = re.sub(r',\s*]', ']', json_str)
        
        questions = json.loads(json_str)
        
        if len(questions) != 10:
            return f"Expected 10 questions, found {len(questions)}."
            
        for i, q in enumerate(questions):
            if 'question' not in q or 'options' not in q or 'answer' not in q or 'explanation' not in q:
                return f"Question {i+1} is missing required fields."
            if len(q['options']) != 4:
                return f"Question {i+1} has {len(q['options'])} options instead of 4."
            if not (0 <= q['answer'] <= 3):
                return f"Question {i+1} answer index {q['answer']} is out of bounds."
                
        return "OK"
        
    except json.JSONDecodeError as e:
        return f"JSON Parse Error: {str(e)}"
    except Exception as e:
        return f"Error: {str(e)}"

results = {}
all_ok = True
for file in sorted(files):
    filepath = os.path.join(exam_dir, file)
    status = validate_quiz_file(filepath)
    results[file] = status
    if status != "OK":
        all_ok = False

for f, status in results.items():
    print(f"{f}: {status}")

if all_ok:
    print("\nAll files passed structural validation!")
else:
    print("\nSome files have errors.")
